import React from 'react'
import './Manager.css'

function Manager() {
    return (
        <div className='manager_maindiv'>
            <div className='manager_container'>
                <div className='manager_div1'>
                    <div className='manager_innerdiv1'>
                        Manager Name
                        <input type="text" placeholder='Enter Manager Name' className='manager_text1'></input>
                    </div>
                    <div className='manager_innerdiv2'>
                        Team name
                        <input type="text" placeholder='Enter Team Name' className='manager_text2'></input>
                    </div>
                </div>
                <div className='manager_div2'>
                    
                    <div className='button_div2'>
                        <button id="save" className='manager_button'>Save</button>
                    </div>
                </div>
            </div>
            <div><hr></hr></div>
            <div className='pay_div1'>
                Amount To Pay
                
                <input className='pay_text' id="amount" type="text" placeholder='Enter Amount'></input>
                <button id ="save1" className='pay_button1'>Save</button>

            </div>
            <div className='pay_details' name="pay">Manager Payment
            </div>
            <div>
                <div className='manager_pay'>
                    Payment
                    <select className='manager_select'>
                        <option value="manager1">Manager 1</option>
                        <option value="manager 2">Manager 2</option>
                    </select>
                </div>
                <div className='manager_pay'>
                    Amount
                    <input className='manager_text' placeholder='Enter Amount' type="text" ></input>
                    <button id="save2" className='pay_button1'>Save</button>
                </div>

            </div>
            <div className='manager_overview' name="pay">Manager list and overview
            </div>
            <div className='col-12'>
                    <div className='manager_list'>
                        <div className='manager_item clearfix'>
                            <div className='col-2 inline_display'>
                                Manager Name
                            </div>
                            <div className='col-2 inline_display'>
                                Team Name
                            </div>
                            <div className='col-2 inline_display'>
                                Amount To Pay
                            </div>
                            <div className='col-2 inline_display'>
                                Paid
                            </div>
                            <div className='col-2 inline_display'>
                                Left
                            </div>
                        </div>
                        <div className='manager_item clearfix'>
                            <div className='col-2 inline_display'>
                                Abhishek
                            </div>
                            <div className='col-2 inline_display'>
                                cdac fc
                            </div>
                            <div className='col-2 inline_display'>
                                1000
                            </div>
                            <div className='col-2 inline_display'>
                                200
                            </div>
                            <div className='col-2 inline_display'>
                                autogenerated
                            </div>
                            <div className='col-2 inline_display'>
                                <button  style={{fontSize:'0.3vw',float:"right",fontSize:'1.2vw'}}>Delete</button>
                              
                            </div>
                        </div>

                    </div>
                </div>
        </div>



    )
}

export default Manager
